### PR TITLE
Use parking_lot 0.5.x

### PR DESCRIPTION
**Pull request by messense**

### CODE REVIEW

**Comment by jethrogb** [comment]
Do you agree this is a backwards-incompatible change, semver-wise?

**Comment by messense** [comment]
I agree. But for 0.x versions, it does not matter that much. Also there are no dependent crates on [crates.io](https://crates.io/crates/namedlock) as of now, it should be fine to do this backwards-incompatible change.

**Comment by messense** [comment]
Actually, since parking_lot isn't exposed in public API, it's not really backwards-incompatible change.

**Comment by jethrogb** [comment]
Sorry for letting this slide. The types are part of the public API of `mod ownedmutexguard`. If you bump this crate's version to 0.6 I'll merge it and publish a new version.

**Comment by jethrogb** [comment]
Thanks!

**Comment by jethrogb** [comment]
Thanks! https://crates.io/crates/namedlock

**Pull request merged**
