### PR TITLE
Add optional parking_lot feature

### PR DESCRIPTION
**Pull request by messense**
https://github.com/Amanieu/parking_lot

### CODE REVIEW

**Comment by jethrogb** [comment]
Thanks for the PR!

Can you add a line that errors when both `spin` and `parking_lot` are selected?

**Comment by messense** [comment]
@jethrogb You mean add that to documentation?

**Comment by jethrogb** [comment]
No, something like this:

https://github.com/jethrogb/rand/blob/b052c17960b8e8ead7af61acc07fbbc2b7458792/src/lib.rs#L256-L257

You can also use a const with a type error instead of a use statement.

**Comment by messense** [comment]
@jethrogb I think it already errors when both features are selected?

```
cargo build --features parking_lot,spin
   Compiling namedlock v0.5.0 (file:///Users/messense/Projects/namedlock-rs)
error[E0252]: the name `Mutex` is defined multiple times
   --> src/lib.rs:119:49
    |
118 | #[cfg(feature="spin")] use spin::{Mutex,MutexGuard};
    |                                   ----- previous import of the type `Mutex` here
119 | #[cfg(feature="parking_lot")] use parking_lot::{Mutex,MutexGuard};
    |                                                 ^^^^^ `Mutex` reimported here
    |
    = note: `Mutex` must be defined only once in the type namespace of this module

error[E0252]: the name `MutexGuard` is defined multiple times
   --> src/lib.rs:119:55
    |
118 | #[cfg(feature="spin")] use spin::{Mutex,MutexGuard};
    |                                         ---------- previous import of the type `MutexGuard` here
119 | #[cfg(feature="parking_lot")] use parking_lot::{Mutex,MutexGuard};
    |                                                       ^^^^^^^^^^ `MutexGuard` reimported here
    |
    = note: `MutexGuard` must be defined only once in the type namespace of this module

error[E0252]: the name `Mutex` is defined multiple times
  --> src/ownedmutexguard.rs:61:49
   |
60 | #[cfg(feature="spin")] use spin::{Mutex,MutexGuard};
   |                                   ----- previous import of the type `Mutex` here
61 | #[cfg(feature="parking_lot")] use parking_lot::{Mutex,MutexGuard};
   |                                                 ^^^^^ `Mutex` reimported here
   |
   = note: `Mutex` must be defined only once in the type namespace of this module

error[E0252]: the name `MutexGuard` is defined multiple times
  --> src/ownedmutexguard.rs:61:55
   |
60 | #[cfg(feature="spin")] use spin::{Mutex,MutexGuard};
   |                                         ---------- previous import of the type `MutexGuard` here
61 | #[cfg(feature="parking_lot")] use parking_lot::{Mutex,MutexGuard};
   |                                                       ^^^^^^^^^^ `MutexGuard` reimported here
   |
   = note: `MutexGuard` must be defined only once in the type namespace of this module

warning: unused imports: `MutexGuard`, `Mutex`
   --> src/lib.rs:119:49
    |
119 | #[cfg(feature="parking_lot")] use parking_lot::{Mutex,MutexGuard};
    |                                                 ^^^^^ ^^^^^^^^^^
    |
    = note: #[warn(unused_imports)] on by default

warning: unused imports: `MutexGuard`, `Mutex`
  --> src/ownedmutexguard.rs:61:49
   |
61 | #[cfg(feature="parking_lot")] use parking_lot::{Mutex,MutexGuard};
   |                                                 ^^^^^ ^^^^^^^^^^

error: aborting due to 4 previous errors

error: Could not compile `namedlock`.

To learn more, run the command again with --verbose.
```

**Comment by jethrogb** [comment]
That's right, but that error message wouldn't be very clear to users of this crate.

**Comment by messense** [comment]
How about this:

```diff
diff --git a/src/lib.rs b/src/lib.rs
index 953b950..aeb5c09 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -104,6 +104,9 @@

 #[cfg(all(test,not(feature="std")))] #[macro_use] extern crate std;

+#[cfg(all(feature="spin",feature="parking_lot"))]
+compile_error!("`spin` and `parking_lot` features can't be used together");
+
 #[cfg(feature="spin")] extern crate spin;
 #[cfg(feature="parking_lot")] extern crate parking_lot;
 #[cfg(feature="std")] extern crate core;
```

errors:

```
cargo build --features parking_lot,spin
   Compiling namedlock v0.5.0 (file:///Users/messense/Projects/namedlock-rs)
error[E0252]: the name `Mutex` is defined multiple times
   --> src/lib.rs:122:49
    |
121 | #[cfg(feature="spin")] use spin::{Mutex,MutexGuard};
    |                                   ----- previous import of the type `Mutex` here
122 | #[cfg(feature="parking_lot")] use parking_lot::{Mutex,MutexGuard};
    |                                                 ^^^^^ `Mutex` reimported here
    |
    = note: `Mutex` must be defined only once in the type namespace of this module

error[E0252]: the name `MutexGuard` is defined multiple times
   --> src/lib.rs:122:55
    |
121 | #[cfg(feature="spin")] use spin::{Mutex,MutexGuard};
    |                                         ---------- previous import of the type `MutexGuard` here
122 | #[cfg(feature="parking_lot")] use parking_lot::{Mutex,MutexGuard};
    |                                                       ^^^^^^^^^^ `MutexGuard` reimported here
    |
    = note: `MutexGuard` must be defined only once in the type namespace of this module

error[E0252]: the name `Mutex` is defined multiple times
  --> src/ownedmutexguard.rs:61:49
   |
60 | #[cfg(feature="spin")] use spin::{Mutex,MutexGuard};
   |                                   ----- previous import of the type `Mutex` here
61 | #[cfg(feature="parking_lot")] use parking_lot::{Mutex,MutexGuard};
   |                                                 ^^^^^ `Mutex` reimported here
   |
   = note: `Mutex` must be defined only once in the type namespace of this module

error[E0252]: the name `MutexGuard` is defined multiple times
  --> src/ownedmutexguard.rs:61:55
   |
60 | #[cfg(feature="spin")] use spin::{Mutex,MutexGuard};
   |                                         ---------- previous import of the type `MutexGuard` here
61 | #[cfg(feature="parking_lot")] use parking_lot::{Mutex,MutexGuard};
   |                                                       ^^^^^^^^^^ `MutexGuard` reimported here
   |
   = note: `MutexGuard` must be defined only once in the type namespace of this module

error: `spin` and `parking_lot` features can't be used together
   --> src/lib.rs:108:1
    |
108 | compile_error!("`spin` and `parking_lot` features can't be used together");
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 5 previous errors

error: Could not compile `namedlock`.

To learn more, run the command again with --verbose.
```

https://doc.rust-lang.org/std/macro.compile_error.html

**Comment by jethrogb** [comment]
Yeah that looks good!

**Comment by messense** [comment]
Ping, can we merge this if there are no other concerns?

**Comment by jethrogb** [comment]
Whoops, sorry for the delay, and thanks for the PR!

**Comment by messense** [comment]
Would be great to have it released on crates.io. :-)

**Comment by jethrogb** [comment]
Yup, done :)

**Pull request merged**
